### PR TITLE
Add JWT_ENABLED config option

### PR DESCRIPTION
**Pull request by heckad**
Add ability for enabling and disabling JWTManager

### CODE REVIEW

**Comment by heckad** [comment]
@vimalloc?

**Comment by vimalloc** [comment]
I am out of town this weekend. I’ll try to review this in the next couple days.

**Comment by vimalloc** [comment]
I'm not sure if this idea belongs as a proper option in this extension. If we just skip grabbing and processing the JWT when `JWT_ENABLED = False` then any endpoint that required on the JWT being present (anything using `current_user`, `get_jwt_claims`, etc) would not work inside your endpoint and could lead to unexpected behavior.

If you want this feature for unit testing, an alternate approach would be to break out the endpoint handler and the logic the endpoint is handling into separate functions, then the function that handles your logic could be unit tested while being completely isolated from flask-jwt-extended. For example:

```python
@app.route('/foo')
@jwt_required
def foo():
    user = get_current_user()
    return handle_foo_request(user)

# This is no longer reliant on flask-jwt-extended and easy to unit test in isolation
def handle_foo_request(user):
    if user != 'admin':
        return jsonify(access='denied'), 401
    return jsonify(access='granted')
```

If you need `JWT_ENABLED` type behavior for other reasons specific to your app, you could create a custom decorator to handle that specifically for your app, something along the lines of:

```python
def custom_jwt_required(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if current_app.config["JWT_ENABLED"]:
            verify_jwt_in_request()
        return fn(*args, **kwargs)
    return wrapper
```

**Comment by heckad** [comment]
> If we just skip grabbing and processing the JWT when `JWT_ENABLED = False` then any endpoint that required on the JWT being present (anything using `current_user`, `get_jwt_claims`, etc)

If we set `False` to  `JWT_ENABLED` then we understand that abilities of this extension (current_user, get_jwt_claims, etc) didn't work. This is a conscious choice that we make ourselves.

**Comment by carc1n0gen** [comment]
> If we set False to JWT_ENABLED then we understand that abilities of this extension (current_user, get_jwt_claims, etc) didn't work. This is a conscious choice that we make ourselves.

That would require quite a lot of extra code everywhere we use those things to check if they are not `None` or something.

**Comment by heckad** [comment]
Imagine that you didn't write `jwt = JWTManager(app)`. You will get the same errors or even more using features from `flask-jwt-extended`. This feature does the same thing, only with the ability to control it at runtime and without changing the source code. (Remove  `jwt = JWTManager(app)` and `jwt_required`, `jwt_optional`, `fresh_jwt_required`, `jwt_refresh_token_required`)

**Comment by carc1n0gen** [comment]
A configuration variable that allows me to consciously choose to make my app just not work sounds useless to me.

I really doubt a mass number of people would ever need this.  Just wrap your `jwt = JWTManager(app)` in a condition in your own app.

Obviously I'm no kind of authority in this project.  Just backing up what @vimalloc has already said.

**Comment by heckad** [comment]
It is not always possible to override `JWTManager(app)`. For example `flask-appbuilder`.

**Comment by vimalloc** [comment]
I stand by my initial thought that this doesn't belong as an option in this extension. I believe that for most users this would cause more issues then it solved. I would instead suggest building some wrappers in your application that that allowed you to enable or disable token checking for your specific needs. Making a custom decorator (https://flask-jwt-extended.readthedocs.io/en/latest/custom_decorators.html) would let you control if token were checked at runtime without having to modify code.

**Pull request closed without merging**
