### PR TITLE
relax config type check on JWT_*_TOKEN_EXPIRES

### LINKED ISSUE #214: relax datetime.timedelta check on JWT_*_TOKEN_EXPIRES envs?
I tried using a [dateutil.relativedelta](https://dateutil.readthedocs.io/en/stable/relativedelta.html) object for the value of JWT_ACCESS_TOKEN_EXPIRES, but the identity checks in config.py prevent it. It's not urgent for us to actually use relativedelta here, but I wanted to go ahead and see if the check could be relaxed.

For reference, the current JWT_*_TOKEN_EXPIRES validity checks look like:

    delta = current_app.config['JWT_ACCESS_TOKEN_EXPIRES']
    if not isinstance(delta, datetime.timedelta) and delta is not False:
        err = 'JWT_ACCESS_TOKEN_EXPIRES must be a datetime.timedelta or False'
        raise RuntimeError(err)
    return delta

It _seems_ like both of the checks could just try to add the value to a datetime object. Something along the lines of:

    delta = current_app.config['JWT_ACCESS_TOKEN_EXPIRES']
    if delta != False:
        try:
            delta + datetime.datetime.now()
        except TypeError as e:
            err = 'must be able to add JWT_ACCESS_TOKEN_EXPIRES to datetime.datetime'
            raise RuntimeError(err) from e
    return delta

This would produce tracebacks like:

    Traceback (most recent call last):
      File "<console>", line 2, in <module>
    TypeError: unsupported operand type(s) for +: 'int' and 'datetime.datetime'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<console>", line 5, in <module>
    RuntimeError: must be able to add JWT_ACCESS_TOKEN_EXPIRES to datetime.datetime

### PR DESCRIPTION
**Pull request by abathur**
Instead of requiring JWT_ACCESS_TOKEN_EXPIRES and JWT_REFRESH_TOKEN_EXPIRES to
be of type `datetime.timedelta` or `False`, checks in config.py support any
value that can be successfully added to a `datetime.datetime` object.

Closes #214.

(I'm not well-configured to test this atm, so I'm relying on CI to slap me down if there's a problem here.)

### CODE REVIEW

**Comment by vimalloc** [comment]
Nice :+1: Could you add a unit test for the `dateutil.relativedelta`? You can include that package in the requirements.txt

**Comment by abathur** [comment]
I was just about to ask; I wasn't sure if you'd want the extra dependency or not. :)

**Comment by vimalloc** [comment]
For sure, thanks for checking :+1: Having the extra development dependency doesn't bother me at all. 

Thanks for contributing!

**Comment by vimalloc** [comment]
Oh, that reminds me. With the added requirement of the `six` package, could you also update the install requirements here (https://github.com/vimalloc/flask-jwt-extended/blob/master/setup.py#L31) to list `six` as well?

Cheers.

**Comment by vimalloc** [comment]
Whoops, I totally forgot that tox used it's own dependencies as well. Gotta love dependency management right?

If you add six and dateutils to the tox.ini I expect these tests should pass :+1:

**Comment by vimalloc** [comment]
Actually, only `dateutil`. Six will be installed because it's part of the setup.py now :+1:

**Comment by abathur** [comment]
I think I'm missing something about your test setup; dateutil imports were failing with dateutil in requirements.txt, but started working when I added it to deps in tox.ini.

**Comment by vimalloc** [comment]
Yeah, the requirements.txt contains a bunch of additional stuff that isn't needed for unit tests (such as the code to generate documentation or push up new releases to PyPI). For the sake of speed, I have tox setup to only install the necessary requirements for running the unit tests instead of all the code in the requirements.txt.

Thanks for spending the time to put this together, it looks good :+1:

**Comment by vimalloc** [comment]
This has been released in 3.18.0. Cheers.

**Pull request merged**
