### PR TITLE
Add support for cookie 'samesite' option

### PR DESCRIPTION
**Pull request by farshiana**

### CODE REVIEW

**Comment by vimalloc** [comment]
This is great. Thanks for contributing! 👍

**Comment by johaven** [comment]
At this time latest version of Flask does not require Werkzeug 0.14 but an older version.
I got this error with 3.6.0 when set_cookie is called:
```python
TypeError: set_cookie() got an unexpected keyword argument 'samesite'
```

**Comment by vimalloc** [comment]
It looks like the requirements for flask are actually just `Werkzeug>=0.7`, so on a fresh install of flask it should have a sufficiently high version (as of writing `0.14.1`), but if you already have flask installed it may be out of date. That could be fixed by doing an upgrade of `Werkzeug` manually in your virtual environment.

I'm going to add `Werkzeug>=0.14` to the requirements of this extension to help alleviate this. If this is not sufficient to solve this issue I will look at ways to disable the samesite feature on older versions of Werkzeug.

Cheers :)

**Comment by johaven** [comment]
You have right, latest version of Flask requires >=0.7, when i installed the last Flask version Werkzeug 0.14 was not out. Thank you :)

**Comment by johaven** [comment]
Another little request, in documentation could you specify for JWT_COOKIE_SAMESITE section :

> Possible values for the flag are **lax** or **strict**

**Pull request merged**
