### PR TITLE
Include user claims in refresh tokens

### PR DESCRIPTION
**Pull request by roubaeli**
Took a stab at #100 to optionally include user claims in refresh tokens. Feedback will be greatly appreciated but please note that I won't be available to make changes/fixes until Monday.

### CODE REVIEW

**Comment by roubaeli** [comment]
Thanks! That's exactly what I was thinking but I wasn't sure how to go for it without creating another fixture so I wanted to ask first if that's OK? :-)

**Comment by vimalloc** [comment]
I think you can get around having a whole new fixture by setting the app.config in the unit test itself (like this: https://github.com/vimalloc/flask-jwt-extended/blob/master/tests/test_headers.py#L23), but if that doesn't work for any reason feel free to make a new fixture :+1:

**Comment by roubaeli** [comment]
Worked perfectly...I squashed new test with the previous commit so the history is clean :-) Thank you for your help!

**Comment by vimalloc** [comment]
Awesome, thanks! I'll push a new version with these changes. Thanks for contributing! :+1:

**Pull request merged**
