### PR TITLE
Update docs according to #215

### PR DESCRIPTION
**Pull request by illia-v**

### CODE REVIEW

**Comment by vimalloc** [comment]
I'm not actually sure I want to update this. I think `('headers',)` could be a lot more confusing then `['headers']` for people who are not as familiar with python, and tuples or lists should work fine for this setting. Thoughts.

**Comment by illia-v** [comment]
Agree, but `JWT_TOKEN_LOCATION` does default to `('headers',)`.
We can change it to default to just a string and then change the docs. Will it be good?

**Comment by vimalloc** [comment]
It does default to `('headers',)`, but functionally if it defaults to that or `['headers']` doesn't have any real affect for users, and the later is (imo) generally better understood. I don't really want to change it to just `headers` either, as having it displayed as a list/sequence/etc in the documentation makes it easier to see at a glance that you can have multiple token locations instead of just one, without having to read the fine print as it were.

These are my thoughts on the matter, but I would love to hear what you think about that. :+1:

**Comment by vimalloc** [comment]
Should also note I do want to update the documentation to say that you can use a sequence, set, etc instead of just a list for these fields. I think there is absolutely value in that :+1:

**Comment by illia-v** [comment]
No problem in changing it to list :)

**Comment by vimalloc** [comment]
Right on. Thanks again for contributing! :+1:

**Pull request merged**
