### PR TITLE
Add support for specifying cookie domain with JWT_COOKIE_DOMAIN

### PR DESCRIPTION
**Pull request by frnsys**
I need to be able to specify the cookie domain so that I can access the cookies on subdomains; this PR implements an optional `JWT_COOKIE_DOMAIN` config variable which will let that be set.

### CODE REVIEW

**Comment by vimalloc** [comment]
Nice! :) instead of doing the .get(value, None), could you set the default value in jwt manager, just to keep things consistent?

Thanks for contributing! I'll get a new version of this pushed out later tonight 👍

**Comment by frnsys** [comment]
done, thanks for the fast response!

**Comment by vimalloc** [comment]
Perfect, thanks! :) I'll get a new version released before I go to bed tonight. 

Cheers.

**Comment by vimalloc** [comment]
Released as 1.4.1 👍

**Comment by glinskyc** [comment]
I am having trouble getting this feature to work, and the documentation doesn't really explain it.  Could an example please be included in the docs?

**Pull request merged**
