### PR TITLE
Please Reject, see comment

### PR DESCRIPTION
**Pull request by wayneworkman**
In this pull request I've made changes to allow the _decode_jwt_from_request function to accept a list of token types. I've also created a new decorator called jwt_access_or_refresh_required.

The idea of this is to show what I'd like to see - having an endpoint protected by requiring either an access token or a refresh token.

I've **not tested** this code at all - and there is likely a better way of doing it that the project maintainers can do. So I'm asking that the project maintainers look over the changes, consider them, and hopefully come up with a new decorator that can protect with EITHER an access token OR a refresh token.

Thanks,
Wayne

### CODE REVIEW

**Comment by wayneworkman** [comment]
@vimalloc I am using access tokens and refresh tokens uniquely. Users are issued access tokens, embedded Linux devices are issued refresh tokens. I have routes specific to users, and routes specific to devices. One particular route I have is for downloading a file - I currently have it protected with requiring a refresh token because the file is consumed by the embedded devices. However, for review purposes I'd like to enable users to be able to download this file too using the same route that already works.  Without being able to allow for either refresh OR access tokens, I'll need to create two routes that do the same thing and protect each accordingly.

**Comment by vimalloc** [comment]
I wonder if there might be a better way to handle your scenario then using those tokens in different ways like that. Something like the [user loader callback](http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.JWTManager.user_loader_callback_loader), [claims verification callback](http://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.JWTManager.claims_verification_loader) or an extra decorator that [checks permissions or roles]( https://gist.github.com/vimalloc/46bf19ee265957257e919e1459735c99)

**Comment by wayneworkman** [comment]
Most likely yes it can be done better, but I chose to use it as I did because it made a lot of sense at the time. Two different decorator protectors built-in to this project, and I have two different kinds of access to the API, web-users and devices. It just seemed natural to protect routes based on the two kinds of tokens, access and refresh.
I understand this is an opinionated library, and I appreciate that. People need more opinions, need to take more stances on things. If this request isn't inline with the goals that you set out to achieve, don't worry about it. I won't be offended at all. I am merely suggesting an idea, and it's fine if that idea doesn't fit in or make sense.

**Comment by dunkmann00** [comment]
@wayneworkman I think you might be misunderstanding the purpose of a refresh token. Refresh tokens are used to obtain new access tokens without requiring the user to enter his credentials. Whereas access tokens are used to access content that is only meant for verified users (protected). So based on that and your use case, both users and devices should have access tokens if they want to access protected content. I would also suggest checking out the links @vimalloc included in his previous comment, adding some sort of custom claim in the access token seems like it could provide the behavior you're looking for. I hope this helps!

**Pull request closed without merging**
