### PR TITLE
Allow to specify `user_claims` at token creation

### PR DESCRIPTION
**Pull request by jeanphix**

### CODE REVIEW

**Comment by jeanphix** [comment]
Made the requested changes.

**Comment by efake2002** [comment]
This is a great improvement to the lib. Thanks @jeanphix. @vimalloc can you merge this and push a release ASAP? This would be really helpful for a lot of people.

**Comment by vimalloc** [comment]
Sorry, I’ve been crazy busy with personal stuff this week. I’ll find some time this weekend to look over the changes, and get a new release cut if all looks good :+1:

**Comment by efake2002** [comment]
@vimalloc thanks a lot! I know you're busy but I have a _really_ _quick_ question and I would really appreciate you answering it. Since the feature that @jeanphix has implemented in the pull request has not been released, in the meantime, is there any way to dynamically set user claims after creating the token. I am aware of the `@user_loader_callback_loader`, but that adds the claims when the token is made. I'd like to add the claims after the token is created using `create_access_token()`. Any help here? Again, I'm sorry if this is distracting you with your busy day.

**Comment by vimalloc** [comment]
@efake2002 No worries. The work around I would suggest for now until I can get this merged is storing your custom claims in the `flask.g` object before calling `create_access_token`, then in the `user_loader_callback_loader`, read and return data from `flask.g`. It's pretty ugly (this patch will help a lot with this), but it should be totally workable until I can get this merged :+1:

**Comment by efake2002** [comment]
@vimalloc thanks so much! very excited for the next release 😄. have a g'day mate!

**Comment by vimalloc** [comment]
Thank you @jeanphix for your work on this. I'll get a new release cut with this soon :+1:

**Comment by vimalloc** [comment]
This has been released in 3.18.0. Cheers.

**Comment by efake2002** [comment]
@vimalloc thanks a lot for releasing this so quickly brother. You're the best! @jeanphix thanks for the great feature. Open source fricken rocks, doesn't it? :)

**Pull request merged**
