### PR TITLE
[compat] Add missing python version in CI test matrix

### PR DESCRIPTION
**Pull request by Djailla**
Remove deprecated python 3.4

Add python 3.7 and 3.8

### CODE REVIEW

**Comment by vimalloc** [comment]
Thanks!

**Comment by Djailla** [comment]
Hello @vimalloc for your information, CI failed when using pypy3. Is this something that would require an issue or a PR ?

**Comment by vimalloc** [comment]
An issue would be great, and a PR would be even better if you have it in you! If not I'll poke at it when I have some time :+1:

**Comment by Djailla** [comment]
Here is the first PR : https://github.com/vimalloc/flask-jwt-extended/pull/293

**Pull request merged**
