### PR TITLE
Asymmetric crypto support

### PR DESCRIPTION
**Pull request by alexykot**
- JWT_PUBLIC_KEY config value added
- symmetric/asymmetric distinction added
- test coverage for asymmetric handling added
- docs updated

### CODE REVIEW

**Comment by vimalloc** [comment]
This is great! Thanks for contributing 👍 

I'll get a new version with this pushed out ASAP.

**Comment by vimalloc** [comment]
Heh. I was the one who added ```jwt.algorithms.requires_cryptography``` to pyjwt. Really cool to see that come full circle.

I released this as 1.5.0. Thinking on it more, I think I want to add a JWT_PRIVATE_KEY config value as well, and have it grab that first and fall back to the secret key of it isn't set, just to make using asymptomatic cryprto clearer in the docs. That sound reasonable to you? 

Cheers.

**Comment by alexykot** [comment]
`JWT_PRIVATE_KEY` makes sense, although I'm not sure about the fallback.
Probably if we're using asymmetric crypto - we should enforce private+public keys rather than a secret key? And make a clear distinction in the docs between symmetric and asymmetric keys usage. Thoughts?

**Comment by vimalloc** [comment]
That sounds reasonable to me.

**Comment by vimalloc** [comment]
Released in version 2.0.0.

We now have to use ```JWT_PRIVATE_KEY``` and ```JWT_PUBLIC_KEY``` for asymmetric algorithms, and added support for ```JWT_SECRET_KEY``` when using symmetric algorithms. ```app.secret_key``` still works for symmetric algorithms as well, but not for asymmetric ones.

Thanks for contributing! 👍

**Pull request merged**
